apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mydeploy
  namespace: argocd
spec: 
  replicas: 2
  selector: 
    matchLabels:
      app: mydeploy
  template: 
    metadata: 
      labels: 
        app: mydeploy
    spec: 
      containers:
        - name: mydeploy
          image: nginx
          ports: 
            - containerPort: 80
            
